# data: '/home/linjunyang/data/lcsts/data/'
data: '/home/xuehp/git/Global-Encoding/data2/'
logF: 'experiments/lcsts/'
epoch: 20
batch_size: 16
optim: 'adam'
cell: 'lstm'
attention: 'luong_gate'
learning_rate: 0.03
max_grad_norm: 10
learning_rate_decay: 0.5
start_decay_at: 6
emb_size: 16
hidden_size: 16
dec_num_layers: 3
enc_num_layers: 3
bidirectional: True
dropout: 0.0
max_time_step: 50
eval_interval: 100
save_interval: 30
metrics: ['bleu']
shared_vocab: True
beam_size: 10
unk: True
schedule: False
selfatt: True
schesamp: False
swish: True
length_norm: True
